name: Run Cypress
# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: cypress-io/github-action@v6
